apiVersion: "apps/v1"
kind: Deployment
metadata:
  name: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello

  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello
          image: "hello-impl:1.0-SNAPSHOT"
          env:
            - name: REQUIRED_CONTACT_POINT_NR
              value: "1"
            - name: JAVA_OPTS
              value: "-Xms256m -Xmx256m -Dconfig.resource=prod-application.conf"
            - name: APPLICATION_SECRET
              value: "changeme"
            - name: CASSANDRA_URL
              value: {{CASSANDRA_URL}}
            - name: KAFKA_BROKER_URL
              value: {{KAFKA_BROKER_URL}}
          ports:
            - name: management
              containerPort: 8558
            - name: kamon-status
              containerPort: 5526
            - name: prom
              containerPort: 9095
          readinessProbe:
            httpGet:
              path: "/ready"
              port: management
            periodSeconds: 10
            failureThreshold: 10
            initialDelaySeconds: 20
          livenessProbe:
            httpGet:
              path: "/alive"
              port: management
            periodSeconds: 10
            failureThreshold: 10
            initialDelaySeconds: 20
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 0.25
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: hello
spec:
  ports:
    - name: http
      port: 80
      targetPort: 9000
    - name: kamon-status
      port: 5266
    - name: prom
      port: 9095
  selector:
    app: hello
  type: NodePort